In [3]:
import numpy as np

In [11]:
# array from 1 to 20
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
# array of 5 zeros
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [15]:
# array of 5 ones
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [19]:
# 5 evenly spaced numbers between 0 and 1
arr= np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [24]:
# multiply all the elements by3
nums = np.array([1,2,3,4])
print(nums)
mul=3*nums
print(mul)

[1 2 3 4]
[ 3  6  9 12]


In [27]:
# add 10 to all numbers
add = nums + 10
print(add)

[11 12 13 14]


In [29]:
# Find square of all the elements
print(nums**2)

[ 1  4  9 16]


In [4]:
# increase salary by 10%
salary = np.array([50000,23000,12000])
inc_salary = salary + (salary * 0.10)
print(inc_salary)


[55000. 25300. 13200.]


In [5]:
# decrease salary by 5%
dec_salary = salary - (salary * 0.10)
print(dec_salary)


[45000. 20700. 10800.]


In [34]:
# square root
a = np.array([4,9,16])
print(np.sqrt(a))

[2. 3. 4.]


In [37]:
# find exponential values
print(np.exp(a))

[5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [41]:
# find sine, cosine, tangent values
n = np.array([np.pi/2,np.pi/3,np.pi/6])
sine = np.sin(n)
print(sine)
cose = np.cos(n)
print(cose)
tane = np.tan(n)
print(tane)

[1.        0.8660254 0.5      ]
[6.12323400e-17 5.00000000e-01 8.66025404e-01]
[1.63312394e+16 1.73205081e+00 5.77350269e-01]


In [48]:
# find sec, cosec, cot,
print(1/sine)
print(1/cose)
print(1/tane)

[1.         1.15470054 2.        ]
[1.63312394e+16 2.00000000e+00 1.15470054e+00]
[6.12323400e-17 5.77350269e-01 1.73205081e+00]


In [7]:
# mean
x = np.array([10000,30000,40000,50000])
print(np.mean(x))

32500.0


In [10]:
# median
print(np.median(x))

35000.0


In [11]:
# maximun
print(np.max(x))

50000


In [13]:
# minimum
print(np.min(x))

10000


In [14]:
# SD
print(np.std(x))

14790.19945774904


In [15]:
# 25th percentile
print(np.percentile(x,25))

25000.0


In [16]:
# 50th percentile
print(np.percentile(x,50))

35000.0


In [17]:
# 75th percentile
print(np.percentile(x,75))

42500.0


In [26]:
marks = np.array([67,50,65,34,40])
# add 5 grade marks
print(marks+5)

# average marks
print(np.average(marks))

#highest marks
print(np.max(marks))

# lowest marks
print(np.min(marks))

# marks >40
pass_std = np.sum(marks>40)
print(pass_std)


[72 55 70 39 45]
51.2
67
34
3


In [30]:
# descibe function

def describe(arr):
    result = {
        "mean": np.mean(arr),
        "std": np.std(arr),
        "min": np.min(arr),
        "max": np.max(arr),
        "median": np.median(arr)
    }

    return result

marks = np.array([20,30,40,50])
summary =describe(marks)

for key, value in summary.items():
    print(f"{key}: {value}")

mean: 35.0
std: 11.180339887498949
min: 20
max: 50
median: 35.0
